<?=$this->doctype?>
<html>
  <head>
    <title>Index &ndash; <?=$this->common_title?></title>
    <meta charset="<?=$this->charset?>" />
  </head>
  <body>
    <nav>
        <ul>
            <li><a href="index.php">Page d'accueil</a></li>
            <li><a href="index.php?page=login">Formulaire d'identification</a></li>
        </ul>
    </nav>
    <p>Ceci est le mot du jour</p>
  </body>
</html>