<!DOCTYPE html>
<html>
    <head>
        <title>Login &ndash; <?=$this->common_title?></title>
        <meta charset="<?=$this->charset?>" />
    </head>
    <body>
        <nav>
            <ul>
                <li><a href="index.php">Page d'accueil</a></li>
                <li><a href="index.php?page=login">Formulaire d'identification</a></li>
            </ul>
        </nav>
	<form action="index.php?page=login" method="post">
            <label for="username">Utilisateur</label><br />
            <input type="text" maxlength="50" name="username" id="username" />
            <br />
            <br />

            <label for="userpass">Mot de passe</label><br />
            <input type="password" maxlength="100" name="userpass" id="userpass" />
            <br />
            <br />

            <input type="submit" value="M'authentifier" />
	</form>  
    </body>
</html>