	<form action="index.php?page=login" method="post">
            <label for="username">Utilisateur</label><br />
            <input type="text" maxlength="50" name="username" id="username" />
            <br />
            <br />

            <label for="userpass">Mot de passe</label><br />
            <input type="password" maxlength="100" name="userpass" id="userpass" />
            <br />
            <br />

            <input type="submit" value="M'authentifier" />
	</form>  
