<!DOCTYPE html>
<html>
  <head>
    <title>Exercice Chapitre 4</title>
    <meta charset="UTF-8" />
  </head>
  <body>
  <table border='1'>
    <thead>
      <tr>
      <th>Nom complet</th>
      <th>Type forfait</th>
      <th>Numéro</th>
      <th>Zone géographique</th>
      <th>Données utilisées / max (Mio)</th>
    </tr>
  <?php
    foreach ($tabClients as $client) {
  ?>
      <tr>
      <td><?=$client->getHtmlFullName()?></td>
      <td><?=$client->getForfait()->getHtmlForfait()?></td>
      <td><?=$client->getHtmlTelephone()?></td>
      <td><?=$client->getHtmlZone()?></td>
      <td>Data<!-- Données utilisées / max (Mio) --></td>
    </tr>
  <?php
  }
  ?>
  </table>
  </body>
</html>
