<!DOCTYPE html>
<html>
  <head>
    <title>PHP Niveau 2</title>
    <meta charset="UTF-8" />
    <style>
        .infos {
            background-color:rgba(220, 150, 150, 0.6);
            text-align: center;
            border:2px solid black;
            border-radius: 20px;
        }
    </style>
  </head>
  <body>
  <nav>
    <?=$this->getMenuTop();?>
  </nav>
  <?=$this->getContent();?>
  </body>
</html>
